/**
 * Business context: defines the structured-clone contract between the map UI
 * and the dedicated dynamic-routing worker. Only plain data crosses this
 * boundary; swissTLM3D cells, graphs, and spatial indexes remain worker-owned.
 */
import type { Coordinate } from 'ol/coordinate.js';
import type {
  RoutedNetworkPath,
  RoutingNetworkPhaseTimings,
} from './networkRouter';

/** Session cache sizes exposed for diagnostics and the local benchmark. */
export interface DynamicRoutingCacheStats {
  /** Raw swissTLM3D cells retained for the current page session. */
  loadedCells: number;
  /** Cell requests currently in flight. */
  pendingCells: number;
  /** Exact corridor graphs retained by the small LRU cache. */
  cachedNetworks: number;
}

/** Detailed local timings collected only by the routing benchmark. */
export interface DynamicRoutingPhaseTimings extends RoutingNetworkPhaseTimings {
  /** Time spent calculating the exact graph-cache key and searching the LRU. */
  graphCacheLookupDurationMs: number;
  /** Time spent resolving already-cached raw cells into the requested corridor. */
  rawCellAccessDurationMs: number;
  /** Time spent deduplicating and merging road and hiking features from cells. */
  featureMergeDurationMs: number;
  /** Time spent constructing RoutingNetwork nodes, edges, and spatial indexes. */
  graphBuildDurationMs: number;
  /** Number of exact corridor graphs reused from the session LRU. */
  graphCacheHits: number;
  /** Number of exact corridor graphs that had to be constructed. */
  graphCacheMisses: number;
  /** Number of narrow or retry corridor route attempts. */
  routeAttempts: number;
  /** Whether the wider fallback corridor was required. */
  retryUsed: boolean;
}

/** Routed result together with phase timings for one benchmarked section. */
export interface DiagnosedDynamicRoutingResult {
  /** Routed geometry, or `null` when both corridors fail. */
  path: RoutedNetworkPath | null;
  /** Aggregated timings across the initial and optional retry corridor. */
  timings: DynamicRoutingPhaseTimings;
}

/** Signals that a route corridor exceeded the bounded browser safety limit. */
export class RoutingAreaTooLargeError extends Error {
  constructor(
    message = 'The requested dynamic routing area contains too many swissTLM3D cells.',
  ) {
    super(message);
    this.name = 'RoutingAreaTooLargeError';
  }
}

/** Request that snaps one first waypoint. */
export interface SnapWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the main-thread facade. */
  requestId: number;
  /** Worker operation selected for this message. */
  operation: 'snap';
  /** User-selected EPSG:2056 coordinate to project onto the local network. */
  coordinate: Coordinate;
}

/** Request that routes one section. */
export interface RouteWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the main-thread facade. */
  requestId: number;
  /** Worker operation selected for this message. */
  operation: 'route';
  /** Existing editable-route endpoint in EPSG:2056. */
  startCoordinate: Coordinate;
  /** Newly selected destination in EPSG:2056. */
  endCoordinate: Coordinate;
}

/** Benchmark-only route request that returns worker-side phase timings. */
export interface DiagnosedRouteWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the benchmark facade. */
  requestId: number;
  /** Diagnostic operation excluded from the normal application path. */
  operation: 'routeWithDiagnostics';
  /** Existing route endpoint in EPSG:2056. */
  startCoordinate: Coordinate;
  /** Synthetic benchmark destination in EPSG:2056. */
  endCoordinate: Coordinate;
}

/** Request that clears only derived graphs while retaining downloaded cells. */
export interface ClearNetworkCacheWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the benchmark facade. */
  requestId: number;
  /** Diagnostic operation that preserves the expensive raw-cell cache. */
  operation: 'clearNetworkCache';
}

/** Request that reads worker-owned cache sizes. */
export interface CacheStatsWorkerRequest {
  /** Discriminator for an operation that expects a response. */
  type: 'request';
  /** Correlation identifier generated by the benchmark facade. */
  requestId: number;
  /** Diagnostic operation that returns immutable cache counts. */
  operation: 'getCacheStats';
}

/** Cancels one outstanding operation. */
export interface CancelRoutingWorkerRequest {
  /** Discriminator handled without creating another worker operation. */
  type: 'cancel';
  /** Identifier of the request whose AbortController must be triggered. */
  requestId: number;
}

/** Every message accepted by the worker. */
export type RoutingWorkerRequest =
  | SnapWorkerRequest
  | RouteWorkerRequest
  | DiagnosedRouteWorkerRequest
  | ClearNetworkCacheWorkerRequest
  | CacheStatsWorkerRequest
  | CancelRoutingWorkerRequest;

/** Serialized error safe to pass through structured clone. */
export interface SerializedRoutingWorkerError {
  /** Error class name used to reconstruct typed failures on the main thread. */
  name: string;
  /** Human-readable failure message shown or handled by the caller. */
  message: string;
  /** Optional worker-side stack retained for development diagnostics. */
  stack?: string;
}

/** Successful worker response. */
export interface RoutingWorkerSuccessResponse {
  /** Response discriminator used by the main-thread facade. */
  type: 'success';
  /** Identifier of the request promise to resolve. */
  requestId: number;
  /** Structured-clone-safe result whose concrete type depends on the operation. */
  result: unknown;
}

/** Failed worker response. */
export interface RoutingWorkerErrorResponse {
  /** Response discriminator used by the main-thread facade. */
  type: 'error';
  /** Identifier of the request promise to reject. */
  requestId: number;
  /** Plain-data error reconstructed by the main-thread client. */
  error: SerializedRoutingWorkerError;
}

/** Every response emitted by the worker. */
export type RoutingWorkerResponse =
  | RoutingWorkerSuccessResponse
  | RoutingWorkerErrorResponse;
